// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbFvTI-sKBwSwd8iVwouDByPNJimoogT8',
    appId: '1:357525072398:web:aeba5bbfc70a8435c96a5f',
    messagingSenderId: '357525072398',
    projectId: 'gashome-66c08',
    authDomain: 'gashome-66c08.firebaseapp.com',
    storageBucket: 'gashome-66c08.firebasestorage.app',
    measurementId: 'G-1SXJ6G4DG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAleE-bMop7exBXtoRDSqU3vCbPiIKqoPY',
    appId: '1:357525072398:android:ee76bad04a5b0a12c96a5f',
    messagingSenderId: '357525072398',
    projectId: 'gashome-66c08',
    storageBucket: 'gashome-66c08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN6r3KTp8fNL-Nwu8LvFr1wFqD7bc4mSY',
    appId: '1:357525072398:ios:0f5b182c67f4632dc96a5f',
    messagingSenderId: '357525072398',
    projectId: 'gashome-66c08',
    storageBucket: 'gashome-66c08.firebasestorage.app',
    iosBundleId: 'com.example.gazhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN6r3KTp8fNL-Nwu8LvFr1wFqD7bc4mSY',
    appId: '1:357525072398:ios:0f5b182c67f4632dc96a5f',
    messagingSenderId: '357525072398',
    projectId: 'gashome-66c08',
    storageBucket: 'gashome-66c08.firebasestorage.app',
    iosBundleId: 'com.example.gazhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbFvTI-sKBwSwd8iVwouDByPNJimoogT8',
    appId: '1:357525072398:web:df3763435b1be715c96a5f',
    messagingSenderId: '357525072398',
    projectId: 'gashome-66c08',
    authDomain: 'gashome-66c08.firebaseapp.com',
    storageBucket: 'gashome-66c08.firebasestorage.app',
    measurementId: 'G-X3FBB0Z0Y4',
  );
}
