class LangLocal{
  Map langLocal={
    "Skip" : {"en":"Skip" , "ar":"تخطي"},
    "Next" : {"en":"Next" , "ar":"التالي"},
    "Welcome" : {"en":"Welcome to" , "ar":"مرحبا بك في "},
    "DBoard1" : {"en":"Your ideal destination for obtaining gas cylinders easily and safely. With us, stop the hassle of searching, and enjoy a fast and convenient ordering experience that meets your daily needs." , "ar":"وجهتك المثالية للحصول على أسطوانات الغاز بسهولة وأمان. معنا، ودّع عناء البحث، واستمتع بتجربة طلب سريعة ومريحة تلبي احتياجاتك اليومية."},
    "Why" : {"en":"Why choose us?!","ar":"لماذا تختارنا ؟!"},
    "DBoard2" : {"en":"Super-speed: delivery in record time. Guaranteed safety: high-quality products with the best standards. Complete comfort: continuous support and personalized service to meet all your requests. We are here to make your life easier and make your needs closer than you can imagine!" , "ar": "سرعة فائقة: توصيل في وقت قياسي. أمان مضمون: منتجات عالية الجودة بأفضل المعايير. راحة تامة: دعم متواصل وخدمة مخصصة لتلبية كل طلباتك. نحن هنا لتسهيل حياتك وجعل احتياجاتك أقرب مما تتخيل!"},
    "Redy" : {"en":"Ready to start?","ar":"جاهز للبدء؟"},
    "DBoard3" : {"en":"All you have to do is choose your cylinder, complete the order, and leave the rest to us! Enjoy professional service, fast delivery, and a unique experience that you will not forget. Start now and become part of our trusted family!","ar":"كل ما عليك فعله هو اختيار أسطوانتك، وإتمام الطلب، ودع الباقي علينا! استمتع بخدمة احترافية، توصيل سريع، وتجربة مميزة لن تنساها. ابدأ الآن وكن جزءًا من عائلتنا الموثوقة!"},
    "Sign Up" : {"en":"Sign Up","ar":"انشاء حساب"},
    "Sign In" : {"en":"Sign In","ar":"تسجيل دخول"},
    "phone" : {"en":"Enter phone number","ar":"ادخل رقم الهاتف"},
    "pass" : {"en":"Enter your password","ar":"ادخل الرقم السري"},
    "cpass" : {"en":"Confirm password","ar":"تاكيد كلمة المرور"},
    "forget" : {"en":"Forgot your password?","ar":"هل نسيت كلمة المرور؟"},
    "fname" : {"en":"first name","ar":"الاسم الاول"},
    "sname" : {"en":"last name","ar":"الاسم الثاني"},
    "donesignup" : {"en":"The account has been registered successfully","ar":"تم تسجيل الحساب بنجاح"},
    "completed" : {"en":"completed","ar":'تم'},
    "reset" : {"en":"Reset password","ar": "إعادة تعيين كلمة المرور"},
    "ok" : {"en":"Ok","ar": "موافق"},
    "donereset" : {"en":"A confirmation number has been sent to my account","ar":" تم إرسال رقم تأكيد للحساب علي" },
    "completeaccount" : {"en":"The account was created successfully\nConfirm your account from the message sent via phone","ar":"تم إنشاء الحساب بنجاح \n قم بتأكيد حسابك من الرسالة المرسلة عبر الهاتف" },
    "completeaccountenternumper" : {"en":"Enter your confirmation number","ar":"قم بإدخال رقم التأكيد الخاص بك" },
    "home" : {"en":"Home","ar":"الصفحة الرئيسية"},
    "cart" : {"en":"Cart","ar":"عربة التسوق"},
    "account" : {"en":"Account","ar":"الحساب"},
    "support" : {"en":"Support","ar":"خدمة العملاء"},
    "completepay" : {"en":"Complete purchase","ar":"اتمام عملية الشراء"},
    "orders" : {"en":"Orders","ar":"الطلبيات"},
    "supportdescription" : {"en":"Welcome to the Gazhome app customer service. We are here to serve you and answer any questions or help you solve any problem you face while using the app. Our team is ready to support you around the clock to ensure a smooth and comfortable shopping experience.","ar":"مرحبًا بكم في خدمة عملاء تطبيق غازهوم نحن هنا لخدمتكم وللإجابة على أي استفسارات أو مساعدتكم في حل أي مشكلة تواجهونها أثناء استخدام التطبيق.فريقنا جاهز لدعمكم على مدار الساعة لضمان تجربة تسوّق سلسة ومريحة."},
    "contact" : {"en":"Please contact us via","ar": "يرجي التواصل معنا عبر"},
    "lang1" : {"en":'Complaints',"ar": 'الشكاوي'},
    "lang2" : {"en":'Account',"ar":'الحساب'},
    "lang3" : {"en":'My requests',"ar":'طلباتي'},
    "lang4" : {"en":'Book an order',"ar":'حجز طلبية'},
    "lang5" : {"en":"Confirm payment","ar":"تأكيد عملية الدفع"},
    "lang6" : {"en":"Has the amount been paid by the customer?!","ar":"هل تم سداد المبلغ من العميل ؟!"},
    "lang7" : {"en":"Payment not yet made","ar":"لم يتم الدفع بعد"},
    "lang8" : {"en":"Payment made","ar":"تم السداد"},
    "lang9" : {"en":"Confirm deletion","ar":"تأكيد عملية الحذف"},
    "lang10" : {"en":"Do you not want to deliver these students?","ar":"هل لا تريد توصيل هذه الطلبة"},
    "lang11" : {"en":"Back","ar":"رجوع"},
    "lang12" : {"en":"Yes","ar":"نعم"},
    "lang13" : {"en":"Confirm that the customer has not received the order","ar":"تاكيد عدم استلام العميل الطلبية"},
    "lang14" : {"en":"Did the customer refuse to receive the order?","ar":"هل رفض العميل استلام الطلبية"},
    "lang15" : {"en": "Add a new address","ar":"اضافه عنوان جديد"},
    "lang16" : {"en": "SAR","ar":"ريال "},
    "lang17" : {"en": "We would like to inform you that your order from Gazhome is on its way to you! Our team is keen to deliver the order as quickly as possible, and we are following closely to ensure it arrives safely. You will receive a notification as soon as the driver arrives at your location. If you have any questions, do not hesitate to contact us. Thank you for choosing Gazhome, we wish you a comfortable shopping experience with us. Best regards","ar":"نود إبلاغك بأن طلبك من غازهوم في طريقه إليك! فريقنا حريص على إيصال الطلب بأسرع وقت ممكن،ونتابع عن كثب لضمان وصوله بسلام. ستتلقى إشعارًا بمجرد أن يصل السائق إلى موقعك.إذا كانت لديك أي استفسارات، لا تتردد في التواصل معنا.شكرًا لاختيارك غازهوم، ونتمنى لك تجربة تسوق مريحة معنا.مع أطيب التحيات،"},
    "lang18" : {"en": "In history","ar":"في تاريخ "},
    "lang19" : {"en": "Delivery time","ar":"ميعاد التسليم"},
    "lang20" : {"en": "Home","ar": "الرئيسية"},
    "lang21" : {"en": "Order Details","ar": "تفاصيل الطلبية"},
    "lang22" : {"en": "Grand total","ar": "المجموع الكلي"},
    "lang23" : {"en": "tax fees","ar": "رسوم الضرائب "},
    "lang24" : {"en": "Total including tax","ar":  "المجموع الكلي شامل الضريبة"},
    "lang25" : {"en": "Select payment","ar": "حدد عملية الدفع"},
    "lang26" : {"en": "Credit card","ar": "بطاقة الاتمان"},
    "lang27" : {"en": "Add date","ar":"اضف تاريخ"},
    "lang28" : {"en": "Payment in cash upon delivery","ar":"الدفع نقدا عند الإستلام"},
    "lang29" : {"en": "delete","ar":"حذف"},
    "lang30" : {"en": "add to cart","ar":"أضف إلي السلة"},
    "lang31" : {"en": "Complete your location data","ar":"إكمال بيانات موقعك"},
    "lang32" : {"en": "city","ar":"المدينة"},
    "lang33" : {"en": "area","ar":"المنطقة"},
    "lang34" : {"en": "street","ar":"الشارع"},
    "lang35" : {"en": "building number","ar":"رقم المبني"},
    "lang36" : {"en": "call","ar":"اتصال"},
    "lang37" : {"en": "add address","ar":"اضافة عنوان"},
    "lang38" : {"en": "Select Date","ar":"حدد التاريخ"}, 
    "lang39" : {"en": "Driving license number:","ar":"رقم رخصة القيادة :"},
    "lang40" : {"en": "Car license number:","ar": "رقم رخصة السيارة :"},
    "lang41" : {"en": "Car plate number:","ar":"رقم لوحة السيارة :"},
    "lang42" : {"en": "Payment made","ar":"تم السداد"},
    "lang43" : {"en": "Payment not made","ar":" لم يتم السداد"},
    "lang44" : {"en": " number","ar":" عدد"},
    "lang45" : {"en": "Complete order","ar":"إتمام الطلب"},
    "lang46" : {"en": "Order rejected","ar":"رفض الطلبية"},
    "lang47" : {"en": "Non-delivery","ar":"عدم التوصيل"},
    "lang48" : {"en": "Receiving the order","ar":"استلام الطلبية"},
    "lang49" : {"en": "Welcome to the Gazhome app customer service. We are here to serve you and answer any questions or help you solve any problem you face while using the app. Our team is ready to support you around the clock to ensure a smooth and comfortable shopping experience.","ar":"مرحبًا بكم في خدمة عملاء تطبيق غازهوم نحن هنا لخدمتكم وللإجابة على أي استفسارات أو مساعدتكم في حل أي مشكلة تواجهونها أثناء استخدام التطبيق.فريقنا جاهز لدعمكم على مدار الساعة لضمان تجربة تسوّق سلسة ومريحة."},
    "lang50" : {"en": "Please contact us via","ar":"يرجي التواصل معنا عبر"},
    "lang51" : {"en": "Done successfully","ar":"تم بنجاح"},
    "lang52" : {"en": "logout","ar":"الخروج"},
  };
}